### ISSUE TITLE
Memory Leak on Render

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#164]
I've been chasing a severe memory leak since Saturday, that seems to boil down to references internal to DOMVM. The situation is a relatively simple, but large (4148 elements), list of pairs of string rendered in a DIV (translations, source text and target text).

Every render grows memory significantly, until I crash the 32 bit browser at a little under 4 GBs. 

The usage pattern in the debugger from a heap differential looks like this, where it all seems to end with initElement, as if the elements are being cached and never discarded:

![image](https://user-images.githubusercontent.com/8662551/28042691-3d15809c-6583-11e7-8b2c-c25c5463825f.png)

Any thoughts on where to go with this? Is there something my code might be doing to cause old vNode elements to be retained from render to render?

Version 3.0.2.

**Comment by lawrence-dol** [comment]
Also dev-mode yields nothing interesting; only a warning about an unkeyed input, which is uniquely keyed by a containing div.

**Comment by leeoniya** [comment]
the only things in userspace that would affect this is holding references to vnodes or vms in your app. are you doing either of these?

it probably won't come as a big surprise to you that a repro would be 1,000x more useful :)

the SSR bench [1] creates a decent-sized tree with ~2000 nodes and ~200 sub-views. it may be worth setting a redraw interval of 1000ms and watch what happens to the RAM. the dbmonster bench @ 0 mutations generates ~3k nodes on each redraw and is still pretty gentle on the GC. any serious leaks would have been caught there very quickly. it makes me think it's an issue with sub-views, if it's internal at all.

[1] https://github.com/leeoniya/domvm/tree/3.x-dev/demos/bench/ssr

**Comment by lawrence-dol** [comment]
> holding references to vnodes or vms in your app

I'm not, but I'm used to much more capable JVM debuggers for identifying this kind of thing, so I'll triple check.

> it probably won't come as a big surprise to you that a repro would be 1,000x more useful :)

Yep, getting there. I was hoping for some low-hanging fruit to check for first. 

> it makes me think it's an issue with sub-views, if it's internal at all.

I don't have any sub-views in this one -- it's all a single view, one of many that will eventually form a larger overall application as I re-engineer it all to be an AJAX based DOMVM app.

I'll check the things you've suggested and report back here.

**Comment by lawrence-dol** [comment]
Actually, I am thinking it could be an accidental enclosure of each rendered graph. The speed of growth is definitely proportional to the number of elements displayed.

**Comment by leeoniya** [comment]
check out the attached tests.

1. single top level redraw @100ms
2. single top level redraw @100ms + 73ms "Content" subview redraw
3. single top level redraw @100ms + 73ms "Link" subviews redraw (all 200 of them)

all show normal sawtooth GC pattern and no uncontrolled growth. all the benchmarks are ultra-sensitive to poor GC & mem leaks, so i think anything this severe would have shown up by now :/

[memtest.zip](https://github.com/leeoniya/domvm/files/1137303/memtest.zip)

**Comment by lawrence-dol** [comment]
Hmmm. On every redraw, even while idle, I have two listeners added. Which surely explains why the DOM trees remain reachable. However, I only use `onxxx` for listeners, AFAICT.

**Comment by lawrence-dol** [comment]
Hmmm. On every redraw, even while idle, I have two listeners added. Which surely explains why the DOM trees remain reachable. However, I only use `onxxx` for listeners, AFAICT.

**Comment by leeoniya** [comment]
does the problem go away if you re-create the listeners on each redraw inside render?

**Comment by lawrence-dol** [comment]
You mean with a construct like `onclick: [xltPairClick,nsp,xpt]`? That's the only kind I have. Ten handlers, all recreated with every redraw.

**Comment by leeoniya** [comment]
no, if you reference a shared function and the params stay the same then nothing is recreated or rebound. parameterized handlers diff that array between redraws to determine if anything needs to be recreated/rebound.

try using an inline `xltPairClick.bind(...)`. you can also try setting `xltPairClick._raw = true` to prevent domvm from doing any kind of handler wrapping, so it will receive just `e` like a bare event handler.

**Comment by lawrence-dol** [comment]
So, I've narrowed it down to `div` elements:

![image](https://user-images.githubusercontent.com/8662551/28088057-627dab32-6639-11e7-9b6e-949762a0b9cc.png)

This is on a display that started with 26, was expanded to 6508, then to about 12K, then collapsed back to 26.

It looks like all of the `div` elements remain reachable. But I can't see how to get a browser to show me how they are reachable. That is, via which object(s).

**Comment by leeoniya** [comment]
i'd offer help, but there's too little info here :/

if you remove all ev handlers and just invoke redraw externally (or let's say on an internal timer) does the same thing happen?

**Comment by lawrence-dol** [comment]
> i'd offer help, but there's too little info here :/

I appreciate that; at this point I am documenting the adventure for "future generations". I will pursue the avenues you've suggested after I complete the remaining functionality, so at least I can tell the bosses that I'm technically "done".

Also, it looks like it's only a problem with Firefox. I can't replicate the same fault in Chrome.

**Comment by leeoniya** [comment]
do you have views with many of divs that are designed to unmount/remount, rather than being recycled? for that much *dom* to be hanging around, it has to be created in the first place, which suggests you're opting not to recycle combined with something not allowing the discarded dom to be GCd?

**Comment by lawrence-dol** [comment]
The app is for facilitating application translations. So the general structure is:

Namespace, containing a set of translation pairs, where each of several namespaces can be collapsed out of the way when it's complete. Visually:

![image](https://user-images.githubusercontent.com/8662551/28090808-6e0f0d5c-6642-11e7-9325-56fc0ea49900.png)

When the namespace is collapsed, none of it's children are rendered, only one-liner:

![image](https://user-images.githubusercontent.com/8662551/28090868-b00fd5f6-6642-11e7-827a-072fbccef5aa.png)

Each namespace is a div containing it's translations, each translation is a pair of "source language text" then "target language text". Each namespace is keyed and each pair is keyed. No other elements are keyed. Since pairs may be omitted from the next view by either collapsing the namespace or applying a filter, I keyed them to allow efficient identification.

Does that answer the question?

**Comment by leeoniya** [comment]
doesnt seem like anything too crazy. if you get a chance to recreate the minimal structure you use for this, it would help a lot. from your description, this UI is technically simpler than TodoMVC.

**Comment by lawrence-dol** [comment]
First, a [simple replication of the structure on jsfiddle](https://jsfiddle.net/LawrenceDol/oL27ewow/) show no evidence of leaking; I'll need to continue to build it out until it matches my application more and more.

Second, I am not seeing a leak in Chrome, only in Firefox.

Third, the size/pace of the leaking is directly proportional to the DOM elements rendered. Thus, if I collapse all namespaces, or hide all completed translations, they leak is proportionally slower. So there must be some twist that retains DOM references that I am overlooking.

**Comment by leeoniya** [comment]
> First, a simple replication of the structure on jsfiddle show no evidence of leaking;

i really hope that's an artificial stress test and not your actual dom size, btw 😨

**Comment by lawrence-dol** [comment]
Oh, yeah. Typical total translations in all namespaces for a large app is under 5000. I just pulled numbers more or less out of my butt for this.

**Comment by lawrence-dol** [comment]
Not that we expected it to, but just FYI, 3.0.3 has not affected this problem.

**Comment by lawrence-dol** [comment]
I've pretty much confirm that the leak does not exist in Chrome -- it just has some unexpectedly relaxed GC behavior under load that resembles a leak. Give a minute to breath and all the extra memory is reclaimed; also it doesn't climb nearly as rapidly as Firefox does under the same load.

**Comment by leeoniya** [comment]
@lawrence-dol have you had any more time to investigate this?

**Comment by lawrence-dol** [comment]
@leeoniya : Not at present, as I had to deliver it, even with the leak. But I will definitely return to it ASIC.

**Comment by leeoniya** [comment]
it would be good to get a minimal testcase and maybe even open a "Firefox leaks, Chrome does not" bug filed in bugzilla to get some help and maybe a fix to Gecko in the process :)

**Comment by lawrence-dol** [comment]
@leeoniya : I agree and that's my next course of action.

**Comment by leeoniya** [comment]
i did some poking and got a pretty simple repro. i haven't tried it in Firefox, but Chrome definitely shows a buildup of nodes over time. the version that removes/inserts unrecycled nodes leaks, while the static dom node count w/recycling stays flat.

the first thing to try is to do some extra old vtree un-referencing here: https://github.com/leeoniya/domvm/blob/3.x-stable/src/view/dom.js#L62

i wonder if it's enough to set the `el._node = vnode.el = null`

```js
var el = domvm.defineElement;

function ListView() {
  return (vm, list) =>
    el("ul", list.map(item =>
      el("li", item.val)
    ));
}

function randInt(min, max) {
  return Math.floor(Math.random()*(max-min+1)+min);
}

function randColor() {
  return '#'+Math.floor(Math.random()*16777215).toString(16);
}

function makeList(qty) {
  var items = [];
  while (qty--)
    items.push({val: randColor()});
  return items;
}

// no leaks
setTimeout(function() {
  var vm = domvm.createView(ListView, makeList(100)).mount(document.body);

  setInterval(function() {
    vm.update(makeList(100));
  }, 100);
}, 5000);

/* leaks
setTimeout(function() {
  var vm = domvm.createView(ListView, makeList(100)).mount(document.body);

  setInterval(function() {
    vm.update(makeList(randInt(0, 100)));
  }, 100);
}, 5000);
*/
```

**Comment by leeoniya** [comment]
none of the suspects turned out to have any effect :/

the strangest part is that the heap snapshots in chrome don't show any detached nodes, while according to the perf profile, there should be thousands: http://imgur.com/a/YATqh

i asked for some help here: https://www.reddit.com/r/javascript/comments/6rpnj9/memleak_discrepancy_between_chromes_perf_timeline/

**Comment by leeoniya** [comment]
adding `node.el = el._node = node.parent = node.parent.body[node.idx] = null;` into `_removeChild` does help the leaky case reclaiming mem from old vnodes but does nothing to help the Node accumulation. considering that old vtree reclamation is not an issue at all in the non-leaky case, i don't think this partial remedy worth keeping as it should resolve itself when we fix the main cause.

![improved-leak](https://user-images.githubusercontent.com/43234/28993262-0f65eab6-7978-11e7-8217-e1123793f602.png)

**Comment by leeoniya** [comment]
I've been troubleshooting this for a while. I've done 3 implementations of this test and none of them seem immune to the Node buildup:

picodom: https://codepen.io/anon/pen/MvpeKp?editors=0010

![picodom](https://user-images.githubusercontent.com/43234/29049408-5144996c-7b9b-11e7-8df9-3a39eb7d63db.png)

preact: https://codepen.io/anon/pen/wqJWbg?editors=0010

![preact](https://user-images.githubusercontent.com/43234/29049409-5146d1a0-7b9b-11e7-8991-beb711a0dcd9.png)

react: https://codepen.io/anon/pen/NvpRKg?editors=0010

![react](https://user-images.githubusercontent.com/43234/29049407-51444ca0-7b9b-11e7-9856-3d89fa81c512.png)

domvm (with unreferencing tweak):

![domvm](https://user-images.githubusercontent.com/43234/29049406-5135453e-7b9b-11e7-97b9-f86bf2ba22ca.png)

if you look at the total heap size and the amount of time spent scripting, domvm is significantly better on both axes than the rest here. it may be that domvm simply isn't exterting enough memory pressure to trigger a more aggressive GC pattern, so the sawtooth is much longer in domvm compared to the rest.

when i manually trigger GC from the console (at 30s and 50s), you can see that *everything* gets reclaimed:

![domvm-manual](https://user-images.githubusercontent.com/43234/29049410-5147879e-7b9b-11e7-927c-3a849f6d67c9.png)

i've measured both 3.0.6 and the tweaked version in firefox via Process Explorer. i did not see uncontrolled mem usage in either case, but the tweaked version did use noticeably less throughout the test. i'll do a few more of the faster libs and see how they behave:

https://github.com/MithrilJS/mithril.js
https://github.com/thysultan/dio.js
https://github.com/yelouafi/petit-dom

**Comment by lawrence-dol** [comment]
> when i manually trigger GC from the console (at 30s and 50s), you can see that everything gets reclaimed

That's the same behavior I was referring to when I said that Chrome "has some unexpectedly relaxed GC behavior under load that resembles a leak. But, give a minute to breath and all the extra memory is reclaimed"

It's Firefox that seems to never reclaim anything, all the way up to 4 GiB, at which point it crashes, so it can't be a simple failure to apply GC pressure (vs "domvm simply isn't [exerting] enough memory pressure to trigger a more aggressive GC pattern").

**Comment by leeoniya** [comment]
i have not seen Chrome reclaim *any* Nodes by itself, even after the bench completes and is idle, the Node count remains the same. i can only get Chrome to free up the nodes if i manually press the GC trash can in the console.

i also ran this bench with a list of 3000 elements and did not see uncontrollable growth. i agree that there's something else preventing any Node collection, though it doesnt seem possible to have it collect as much as a manual GC trigger, none of the other libs tested so far allow for this - there  is always continuous growth.

the major problem is, i don't see where these Nodes are, they dont show up in heap snapshots, so i have no idea where to look. i think what you're running into is something different than this because i haven't seen anything even close to what you're describing in FF or Chrome, before or after the tweak.

**Comment by lawrence-dol** [comment]
With my actual app, since it renders an editable row, which you can move up and down by pressing the cursor keys, it's pretty trivial to just hold down the arrow-down key and watch memory grow. But, as soon as a stop that, Chrome reclaims, and Chrome never seems to grow beyond a few hundred MiB (on a 32 GiB machine).

In contrast, with Firefox I can't get to the end and back of the list before it crashes; once through the list will be multiple GiB use, and this in a profile with just one extension (FireTitle which only changes the taskbar/titlebar window text).

**Comment by leeoniya** [comment]
i believe you, but i'm flying blind. the Node leak i seem to have found isnt showing up in devtools and the leak you've found i simply can't reproduce. i'm gonna leave this until you can come up with at least a demo that can continuously accumulate mem as you've described.

**Comment by leeoniya** [comment]
i tried did an ivi impl and it looks like this over ~120secs:

![ivi](https://user-images.githubusercontent.com/43234/29108117-2cf22d64-7ca3-11e7-9a53-cda77d215823.png)

domvm:

![domvm](https://user-images.githubusercontent.com/43234/29108131-4083cfcc-7ca3-11e7-8489-d341d55dfc74.png)

i'll need to start picking things apart to see where the gradual accumulation comes from.

**Comment by leeoniya** [comment]
@lawrence-dol can you check if the latest dev version had any effect on your case?

**Comment by lawrence-dol** [comment]
In Firefox it doesn't appear any different. Leaks at a rate of about 100 M/sec. After about 2.5 G, total memory, the browser locks up non-responsive and memory just continues increasing, though at about 200 K/sec. Even if I close the tab.

However, in Google, the application memory is pretty stable overall (viewed in Task Manager) and the heap seems to grow , but the number of nodes and listeners grows continuously.

![image](https://user-images.githubusercontent.com/8662551/29142778-d7fcc124-7d07-11e7-962a-f784b94b6a45.png)

The corresponding activity is (approx seconds start):

  - 0 : Idle, all translation rows collapsed.
  - 5 : Expand all translation rows.
  - 10 : Actively cycling down translation rows with a slight pause around 22 seconds on a special row that needs me to tab before continuing.
  - 30 : Idle.
  - 35 : GC.
  - 40 : Active.
  - 47 : Idle.
  - 51 : GC.
  - 65 : Collapse translation rows and GC.

It makes me wonder if Firefox leaks heap attached to listeners, but Chrome somehow manages to clean up unreachable heap more effectively. Thus, the core problem is the listeners remaining.

I'll see if adding the listeners to my fiddle replicates this.

**Comment by leeoniya** [comment]
the core issue is the Nodes somehow remaining, which in turn leaves the listeners as well. the two trend-lines basically trace each other. we know that nodes remaining has nothing to do with the listerners because in my tests there are no listeners at all.

i'm gonna take the `pico` build and start stripping out any functionality not needed to by my simple test  (eg. refs, attrs, hooks, etc) that still exhibits the node buildup. i've already tried a few things like an un-referencing pass over all `vnode.el` in the old vtree, in case it was still somehow reachable after a redraw.

the whole situation is 10x as annoying because a manual GC invocation cleans everything up, so there *shouldn't* be any reachable code remaining that would justify the accumulation. and none of these phantom nodes show up in the `Containment`/dom areas in devtools. really frustrating.

**Comment by leeoniya** [comment]
mithril does well, too:

![mithril](https://user-images.githubusercontent.com/43234/29146254-e0efdbae-7d25-11e7-871f-8af3cccb25c3.png)

**Comment by lawrence-dol** [comment]
> the whole situation is 10x as annoying because [...] there shouldn't be any reachable code

I completely agree.

But if nodes are accumulating, why isn't heap growing as well? The head GC pattern seems normal and overall size stable.

**Comment by lawrence-dol** [comment]
I've refactored my app code to put the listener on the group element instead of every individual element, which has slowed the leak down by a factor of 100, now leaking about 1 M/sec instead of 100 M.

The usage graph now looks like this:

![image](https://user-images.githubusercontent.com/8662551/29149234-b2d38f5c-7d27-11e7-951c-ca3c7c448982.png)

Notice that the listeners still grow linearly during the period of actively switching from translation to translation. Notice also that the final explicit GC does not reclaim all the listeners, though it appears to reclaim all nodes and heap.

The initial spike in nodes, and then reduction, is from expanding and then collapsing all the translation items.

What happens during "activity" is that a new row of the list becomes editable, so an input field with a change listener is discarded from the previously editable item and added to the newly editable item.

**Comment by leeoniya** [comment]
it appears that heap only measures js objects and dom nodes are measured separately. when i watch the task manager in Chrome during the test, the tab as a whole does climb in memory but Javascript Memory stays pretty flat.

**Comment by lawrence-dol** [comment]
I seem to have replicated the fault with [this fiddle](https://jsfiddle.net/LawrenceDol/oL27ewow/). I hope it's of some help.

![image](https://user-images.githubusercontent.com/8662551/29152190-da4d7bac-7d3a-11e7-9291-2293cda41a58.png)

**Comment by leeoniya** [comment]
so far i have the `pico` build stripped down to just the essentials needed for the test and the the node buildup still exists. until i find why this happens and fix it, more complex cases won't shed more light on the situation. i have high confidence that when this is fixed, the leaks will go away.

thanks a lot for the repro! it'll help validate or invalidate any "fixes".

**Comment by leeoniya** [comment]
i've stripped down everything to the absolute bones needed to accommodate the contrived testcase. the entire lib + test is 245 lines [1] while still exhibiting the leak. now it's small and simple enough for multiple eyeballs.

the next step will be to try replacing `node.el` and `el.node` with es5 getters/setters backed by Map or WeakMap objects and see it helps. both of these constructs are too slow for actual use in the lib, but it might help track down exactly where the issue is.

[1] https://gist.github.com/leeoniya/7622890577f1bc36eee70da368f69dd7

**Comment by leeoniya** [comment]
different combos of the following had either a negative impact or no effect on both perf and mem (both Map and WeakMap flavors):

```js
var mEls = new WeakMap();

Object.defineProperty(VNode.prototype, "el", {
  get: function() {
    return mEls.get(this);
  },
  set: function(el) {
    if (el == null)
      mEls.delete(this);
    else
      mEls.set(this, el);
  },
});

var mNodes = new WeakMap();

Object.defineProperty(Element.prototype, "_node", {
  get: function() {
    return mNodes.get(this);
  },
  set: function(node) {
    if (node == null)
      mNodes.delete(this);
    else
      mNodes.set(this, node);
  },
});
```

**Comment by lawrence-dol** [comment]
Here is [another, slightly altered fiddle](https://jsfiddle.net/LawrenceDol/rwq2cbyb/) which moves the listeners to the container, eliminating the listener/list-element, and reducing the number of listeners to a static and relatively small number.

The results still show the node growth, but prove that it's not associated with *discarded* listeners (I think).

![image](https://user-images.githubusercontent.com/8662551/29184052-c588fc3a-7db9-11e7-9e20-30a62eaf11fb.png)

**Comment by lawrence-dol** [comment]
Another potentially useful bit of information is that my other app, an 80x24 grid for terminal emulation does not exhibit any problems reclaiming nodes when running on either 3.0.6 or 3.x-dev. So this is not a blanket problem with DOMVM; there's something unique about our test case.

The test run changes just under 1000 emulation display screens, where a large percentage of cells in the grid change on each transition. Yet the number of nodes stays flat until the end, where it jumps by 44, before an explicit GC reclaims most everything.

![image](https://user-images.githubusercontent.com/8662551/29191019-141f1fe8-7dd1-11e7-87c6-5744dc38de6f.png)

**Comment by leeoniya** [comment]
the issue happens when dom nodes are created and then removed. the removed nodes (and their directly bound events) stick around without being garbage collected, despite being unreferenced.

there's no issue when dom nodes are reused & mutated in the live dom. you'll see the effect with eg keyed nodes that cannot be recycled and any dom nodes which have to be removed.

**Comment by leeoniya** [comment]
@lawrence-dol i think this issue is now fixed.

![domvm-fixed](https://user-images.githubusercontent.com/43234/29235096-82e161d4-7ec1-11e7-9bea-7a70a059e726.png)

apparently `delete el._node` was needed rather than `el._node = null`. `delete` is likely a stronger signal for the GC to do its thing.

can you please verify?

**Comment by lawrence-dol** [comment]
Hmmm. I am still seeing slow memory growth in Firefox and Chrome, with Chrome's graph still showing nodes steadily climbing. [My fiddle with listeners only on the group](https://jsfiddle.net/LawrenceDol/rwq2cbyb/) is using https://cdn.rawgit.com/leeoniya/domvm/3.x-dev/dist/micro/domvm.micro.js.

![image](https://user-images.githubusercontent.com/8662551/29235784-2e7902dc-7eb7-11e7-8036-dacc3dbbd3d6.png)

**Comment by lawrence-dol** [comment]
One thing I notice now in my app, is that growth in nodes exactly tracks with growth in listeners. Perhaps that suggests a different, separate bug. In my fiddle, the number of listeners stays flat (because I don't have a change listener on the input field).

![image](https://user-images.githubusercontent.com/8662551/29235897-6ae3ca1c-7eb8-11e7-925c-0877cc6be520.png)

**Comment by lawrence-dol** [comment]
OK, by adding a listener to my fiddle, it now shows listeners and nodes tracking together as well.

![image](https://user-images.githubusercontent.com/8662551/29235986-777800b2-7eb9-11e7-8179-bb6120ae9f63.png)

**Comment by leeoniya** [comment]
i'm seeing very different behavior between running the code in jsfiddle and the same code just in a `test.html` file. can you try running the test code outside of jsfiddle and see if you get the following:

![nofiddle](https://user-images.githubusercontent.com/43234/29237944-8b6adf60-7eee-11e7-958a-578ee22d1661.png)

the listeners do seem to be climbing slowly at a rate of about +1/toggle. As they leak, they appear to be leaking some nodes with them. i'll look into this.

**Comment by leeoniya** [comment]
nevermind. incognito mode shows a profile consistent with yours. non-incoginto gives me different profiles almost every other run.

i'm gonna close this thread since it's getting long. i'll open another as a followup.
